{"count":8,"page":1,"page_size":3,"total_pages":3,"periods":[{"id":"2021-5","incidents":[{"id":"8a0c687e","title":"Snapshot failures","date":"2021-05-25T19:37:20.706Z","modified":"2021-05-25T20:47:20.389Z","scheduled":null,"severity":"partial-outage","affectedsystems":["workers"],"resolved":true,"content":"<p>There have been several Sentry exception reports related to the creation of snapshots. We are currently investigating.</p>\n<!--- language code: en -->\n<div class=\"update-block\">\n          <div class=\"update-block-date\">2021-05-25T20:47:20.389Z</div>\n          <div class=\"update-block-content\">\n            <div class=\"update-block-title\">Resolved</div>\n            <div class=\"update-block-body\">\n<p>This appears to be resolved. We are monitoring affected systems closely and investigating the root cause.</p>\n</div></div></div>\n"},{"id":"fa73f960","title":"Slow session start up times","date":"2021-05-18T21:30:32.457Z","modified":"2021-05-18T23:17:16.732Z","scheduled":null,"severity":"degraded-performance","affectedsystems":["broker","workers"],"resolved":true,"content":"<p>Our monitoring is showing slower than normal start up times for session jobs. We're currently investigating.</p>\n<!--- language code: en -->\n<div class=\"update-block\">\n          <div class=\"update-block-date\">2021-05-18T23:17:16.732Z</div>\n          <div class=\"update-block-content\">\n            <div class=\"update-block-title\">Resolved</div>\n            <div class=\"update-block-body\">\n<p>The root cause of this incident was not found. Logs indicated issues with workers connecting to the <code>broker</code> service. The broker pod was deleted (using <code>kubectrl delete pod</code> which automatically recreates a new one). We also deleted the single <code>worker</code> pod running at the time. This resolved the issue and monitoring is showing normal event processing by the <code>overseer</code> service.</p>\n</div></div></div>\n"},{"id":"7556e102","title":"Stencila Hub is unreachable","date":"2021-05-03T18:40:25.284Z","modified":"2021-05-04T00:51:55.840Z","scheduled":null,"severity":"major-outage","affectedsystems":["manager","storage"],"resolved":true,"content":"<p>Attempting to visit Stencila Hub results in a <code>502 Error</code>.</p>\n<!--- language code: en -->\n<div class=\"update-block\">\n          <div class=\"update-block-date\">2021-05-03T19:16:54.777Z</div>\n          <div class=\"update-block-content\">\n            <div class=\"update-block-title\">Monitoring</div>\n            <div class=\"update-block-body\">\n<p>Incident has been resolved. We're monitoring the system and will shortly update\nthis entry with a detailed report on the cause of the problem.</p>\n</div></div></div>\n<div class=\"update-block\">\n          <div class=\"update-block-date\">2021-05-03T22:51:55.840Z</div>\n          <div class=\"update-block-content\">\n            <div class=\"update-block-title\">Resolved</div>\n            <div class=\"update-block-body\">\n<p>In order to start up, Stencila Hub depends on a connection to a NFS data storage service.\nDue to a lost connection with the data store, the Hub experienced errors triggering a\nKubernetes to automatically restart the <code>manager</code> (Hub) service.</p>\n<p>However the <code>storage</code> service, despite not reporting any errors, was unable to be attached\nto the new <code>manager</code> pod, and thus prevented <code>manager</code> from starting up.</p>\n<p>After manually deleting and recreating the the <code>storage</code> service instance,\nthe <code>manager</code> service was able to establish a connection and successfully start up again.</p>\n</div></div></div>\n"}],"order":1,"count":3},{"id":"2021-4","incidents":[{"id":"0d06cd64","title":"Errors creating project Snapshots","date":"2021-04-20T14:43:29.191Z","modified":"2021-04-20T21:32:36.549Z","scheduled":null,"severity":"partial-outage","affectedsystems":["workers"],"resolved":true,"content":"<!--- language code: en -->\n<p>Creating a project Snapshot fails when attempting to pin the Docker container version.</p>\n<div class=\"update-block\">\n          <div class=\"update-block-date\">2021-04-20T21:32:36.549Z</div>\n          <div class=\"update-block-content\">\n            <div class=\"update-block-title\">Resolved</div>\n            <div class=\"update-block-body\">\n<p>The error stemmed from rotating all API tokens after the recent <a href=\"https://about.codecov.io/security-update/\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"external\">CodeCov security incident</a>.\nAfter the tokens were regenerated, some of secrets were not updated in the deployed pods.</p>\n<p>This caused the Worker process to attempt to use the outdated Docker credentials when\npinning the project Snapshot, and hence fail.</p>\n</div></div></div>\n"},{"id":"083a237b","title":"Cluster maintenance","date":"2021-04-18T23:32:01.564Z","modified":"2021-04-19T00:01:19.584Z","scheduled":null,"severity":"under-maintenance","affectedsystems":["router","manager","broker","overseer","monitor","workers","storage","cache"],"resolved":true,"content":"<p>We are reconfiguring our Kubernetes cluster management tool, <a href=\"https://toolkit.fluxcd.io/\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"external\">Flux</a>. While not expected, there may be some instability during this process.</p>\n<!--- language code: en -->\n"}],"order":2,"count":2},{"id":"2020-9","incidents":[{"id":"d5399762","title":"Database maintenance","date":"2020-09-01T21:11:09.187Z","modified":"2021-05-26T21:06:11.920Z","scheduled":null,"severity":"under-maintenance","affectedsystems":["database"],"resolved":true,"content":"<p>We will be changing the configuration of our Postgres database instance at 2020-09-01T23:00UTC. There may be a few minutes of down time for https://hub.stenci.la during this process but running sessions should not be affected.</p>\n<!--- language code: en -->\n<div class=\"update-block\">\n          <div class=\"update-block-date\">2020-09-01T23:09:00.000Z</div>\n          <div class=\"update-block-content\">\n            <div class=\"update-block-title\">Resolved</div>\n            <div class=\"update-block-body\">\n<p>Resizing of the database instance is complete. Our monitoring indicates that https://hub.stenci.la was unavailable for approximately two minutes during this maintenance period.</p>\n</div></div></div>\n"}],"order":9,"count":1}]}