<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom">
    <channel>
        <title>Stencila Status</title>
        <link>https://status.stenci.la</link>
        <description>Status reports for Stencila</description>
        <lastBuildDate>Sat, 26 Jun 2021 00:52:57 GMT</lastBuildDate>
        <docs>http://blogs.law.harvard.edu/tech/rss</docs>
        <generator>Statusfy</generator>
        <atom:link href="https://status.stenci.la/feeds/incidents.en.xml" rel="self" type="application/rss+xml"/>
        <item>
            <title><![CDATA[Slower than normal times for project archiving]]></title>
            <link>https://status.stenci.la/incidents/df45426a</link>
            <guid>https://status.stenci.la/incidents/df45426a</guid>
            <pubDate>Mon, 31 May 2021 07:55:26 GMT</pubDate>
            <content:encoded><![CDATA[<p>There are slower than normal times, and some failures, when archiving projects during snapshots. We are currently working to fix the issue. There may be partial outages of some services during this time.</p>
<!--- language code: en -->
<div class="update-block">
          <div class="update-block-date">2021-05-31T08:35:03.130Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Resolved</div>
            <div class="update-block-body">
<p>This issue has been resolved. It was related to a failure to mount a cloud storage bucket for snapshot archiving. This issue is reoccurring, for unknown reasons, or causes. We are looking into a longer term fix.</p>
</div></div></div>
]]></content:encoded>
        </item>
        <item>
            <title><![CDATA[Snapshot failures]]></title>
            <link>https://status.stenci.la/incidents/8a0c687e</link>
            <guid>https://status.stenci.la/incidents/8a0c687e</guid>
            <pubDate>Tue, 25 May 2021 19:37:20 GMT</pubDate>
            <content:encoded><![CDATA[<p>There have been several Sentry exception reports related to the creation of snapshots. We are currently investigating.</p>
<!--- language code: en -->
<div class="update-block">
          <div class="update-block-date">2021-05-25T20:47:20.389Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Resolved</div>
            <div class="update-block-body">
<p>This appears to be resolved. We are monitoring affected systems closely and investigating the root cause.</p>
</div></div></div>
]]></content:encoded>
        </item>
        <item>
            <title><![CDATA[Slow session start up times]]></title>
            <link>https://status.stenci.la/incidents/fa73f960</link>
            <guid>https://status.stenci.la/incidents/fa73f960</guid>
            <pubDate>Tue, 18 May 2021 21:30:32 GMT</pubDate>
            <content:encoded><![CDATA[<p>Our monitoring is showing slower than normal start up times for session jobs. We're currently investigating.</p>
<!--- language code: en -->
<div class="update-block">
          <div class="update-block-date">2021-05-18T23:17:16.732Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Resolved</div>
            <div class="update-block-body">
<p>The root cause of this incident was not found. Logs indicated issues with workers connecting to the <code>broker</code> service. The broker pod was deleted (using <code>kubectrl delete pod</code> which automatically recreates a new one). We also deleted the single <code>worker</code> pod running at the time. This resolved the issue and monitoring is showing normal event processing by the <code>overseer</code> service.</p>
</div></div></div>
]]></content:encoded>
        </item>
        <item>
            <title><![CDATA[Stencila Hub is unreachable]]></title>
            <link>https://status.stenci.la/incidents/7556e102</link>
            <guid>https://status.stenci.la/incidents/7556e102</guid>
            <pubDate>Mon, 03 May 2021 18:40:25 GMT</pubDate>
            <content:encoded><![CDATA[<p>Attempting to visit Stencila Hub results in a <code>502 Error</code>.</p>
<!--- language code: en -->
<div class="update-block">
          <div class="update-block-date">2021-05-03T19:16:54.777Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Monitoring</div>
            <div class="update-block-body">
<p>Incident has been resolved. We're monitoring the system and will shortly update
this entry with a detailed report on the cause of the problem.</p>
</div></div></div>
<div class="update-block">
          <div class="update-block-date">2021-05-03T22:51:55.840Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Resolved</div>
            <div class="update-block-body">
<p>In order to start up, Stencila Hub depends on a connection to a NFS data storage service.
Due to a lost connection with the data store, the Hub experienced errors triggering a
Kubernetes to automatically restart the <code>manager</code> (Hub) service.</p>
<p>However the <code>storage</code> service, despite not reporting any errors, was unable to be attached
to the new <code>manager</code> pod, and thus prevented <code>manager</code> from starting up.</p>
<p>After manually deleting and recreating the the <code>storage</code> service instance,
the <code>manager</code> service was able to establish a connection and successfully start up again.</p>
</div></div></div>
]]></content:encoded>
        </item>
        <item>
            <title><![CDATA[Errors creating project Snapshots]]></title>
            <link>https://status.stenci.la/incidents/0d06cd64</link>
            <guid>https://status.stenci.la/incidents/0d06cd64</guid>
            <pubDate>Tue, 20 Apr 2021 14:43:29 GMT</pubDate>
            <content:encoded><![CDATA[<!--- language code: en -->
<p>Creating a project Snapshot fails when attempting to pin the Docker container version.</p>
<div class="update-block">
          <div class="update-block-date">2021-04-20T21:32:36.549Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Resolved</div>
            <div class="update-block-body">
<p>The error stemmed from rotating all API tokens after the recent <a href="https://about.codecov.io/security-update/" target="_blank" rel="noopener noreferrer" class="external">CodeCov security incident</a>.
After the tokens were regenerated, some of secrets were not updated in the deployed pods.</p>
<p>This caused the Worker process to attempt to use the outdated Docker credentials when
pinning the project Snapshot, and hence fail.</p>
</div></div></div>
]]></content:encoded>
        </item>
        <item>
            <title><![CDATA[Cluster maintenance]]></title>
            <link>https://status.stenci.la/incidents/083a237b</link>
            <guid>https://status.stenci.la/incidents/083a237b</guid>
            <pubDate>Sun, 18 Apr 2021 23:32:01 GMT</pubDate>
            <content:encoded><![CDATA[<p>We are reconfiguring our Kubernetes cluster management tool, <a href="https://toolkit.fluxcd.io/" target="_blank" rel="noopener noreferrer" class="external">Flux</a>. While not expected, there may be some instability during this process.</p>
<!--- language code: en -->
]]></content:encoded>
        </item>
        <item>
            <title><![CDATA[Database maintenance]]></title>
            <link>https://status.stenci.la/incidents/d5399762</link>
            <guid>https://status.stenci.la/incidents/d5399762</guid>
            <pubDate>Tue, 01 Sep 2020 21:11:09 GMT</pubDate>
            <content:encoded><![CDATA[<p>We will be changing the configuration of our Postgres database instance at 2020-09-01T23:00UTC. There may be a few minutes of down time for https://hub.stenci.la during this process but running sessions should not be affected.</p>
<!--- language code: en -->
<div class="update-block">
          <div class="update-block-date">2020-09-01T23:09:00.000Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Resolved</div>
            <div class="update-block-body">
<p>Resizing of the database instance is complete. Our monitoring indicates that https://hub.stenci.la was unavailable for approximately two minutes during this maintenance period.</p>
</div></div></div>
]]></content:encoded>
        </item>
        <item>
            <title><![CDATA[Session Provisioning]]></title>
            <link>https://status.stenci.la/incidents/76b4af9c</link>
            <guid>https://status.stenci.la/incidents/76b4af9c</guid>
            <pubDate>Mon, 17 Aug 2020 13:44:32 GMT</pubDate>
            <content:encoded><![CDATA[<p>While scaling the Worker pods, an issue with the Kubernetes configuration is preventing Session Jobs from being taken
off the Queue, causing indefinite wait times when attempting to execute a document.</p>
<!--- language code: en -->
]]></content:encoded>
        </item>
        <item>
            <title><![CDATA[Database upgrade]]></title>
            <link>https://status.stenci.la/incidents/58c07b2a</link>
            <guid>https://status.stenci.la/incidents/58c07b2a</guid>
            <pubDate>Sun, 16 Aug 2020 22:27:23 GMT</pubDate>
            <content:encoded><![CDATA[<p>We will be upgrading our database instance at 2020-08-16T23:00UTC. There may be a few minutes of down time during this process.</p>
<!--- language code: en -->
<div class="update-block">
          <div class="update-block-date">2020-08-16T23:22:56.289Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Resolved</div>
            <div class="update-block-body">
<p>The database instance has been upgraded and is operating as expected. Our monitoring indicates that https://hub.stenci.la was unavailable for approximately two minutes during this upgrade.</p>
</div></div></div>
]]></content:encoded>
        </item>
        <item>
            <title><![CDATA[Data migration]]></title>
            <link>https://status.stenci.la/incidents/96b8e9ee</link>
            <guid>https://status.stenci.la/incidents/96b8e9ee</guid>
            <pubDate>Tue, 14 Jul 2020 04:55:15 GMT</pubDate>
            <content:encoded><![CDATA[<p>We are in the process of migrating the Hub from v2 centered on the <code>director</code> service and deployed on the <code>us-nw-1</code> cluster to v3 centered on the <code>manager</code> service (which replaced <code>director</code>) and deployed on the <code>us-ce-1</code> cluster.</p>
]]></content:encoded>
        </item>
        <item>
            <title><![CDATA[Missing environment variable in router service]]></title>
            <link>https://status.stenci.la/incidents/1ba926ca</link>
            <guid>https://status.stenci.la/incidents/1ba926ca</guid>
            <pubDate>Sat, 06 Jun 2020 13:00:00 GMT</pubDate>
            <content:encoded><![CDATA[<p>The <code>router</code> service failed due to the renaming of an environment variable necessary for the upcoming release of v3.0. This change was inadvertently deployed by our Flux-based continuous deployment.</p>
<p>Automatic updates should have been turned off prior to the release of this change.
This has now been <a href="https://github.com/stencila/gaia/commit/b700327c73e3043d7146f6f3048b005daff0f669" target="_blank" rel="noopener noreferrer" class="external">done and all images pinned to version v2.32.1</a>.</p>
<p>Within the <code>us-nw-1</code> cluster we are using Prometheus (deployed as the <code>monitor</code> service) for internal monitoring of services. However, <code>monitor</code> is not yet set up to monitor the <code>router</code> service. We are now using an external site monitoring service (Pingdom) to provide additional monitoring and alerting of https://hub.stenci.la.</p>
]]></content:encoded>
        </item>
        <item>
            <title><![CDATA[Misconfiguration]]></title>
            <link>https://status.stenci.la/incidents/22c742da</link>
            <guid>https://status.stenci.la/incidents/22c742da</guid>
            <pubDate>Wed, 06 May 2020 06:08:24 GMT</pubDate>
            <content:encoded><![CDATA[<p>A misconfiguration in the <code>router</code> service is preventing a rollover to v2.21.0. As far as we are aware this is not affecting any services.</p>
<!--- language code: en -->
<div class="update-block">
          <div class="update-block-date">2020-05-06T06:45:04.965Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Resolved</div>
            <div class="update-block-body">
<p>The <code>router</code> service has been <a href="https://github.com/stencila/gaia/blob/573fe2ec9a6004dede2180256e1e21d8a89233f7/clusters/us-nw-1/flux/router-deployment.yaml#L72" target="_blank" rel="noopener noreferrer" class="external">rolled back to v2.20.7</a>. There was a temporary outage while we resolved this issue. The issue stemmed from the <code>monitor</code> service erroring due to a known issue with Prometheus.
We are looking into fixing that, but also ways to avoid the <code>router</code> baulking if an upstream service is unavailable as happened in this situation: <code> nginx: [emerg] host not found in upstream &quot;monitor&quot; in /etc/nginx/conf.d/default.conf:24</code>.</p>
</div></div></div>
]]></content:encoded>
        </item>
        <item>
            <title><![CDATA[Continuous deployment setup]]></title>
            <link>https://status.stenci.la/incidents/218de212</link>
            <guid>https://status.stenci.la/incidents/218de212</guid>
            <pubDate>Fri, 24 Apr 2020 22:16:47 GMT</pubDate>
            <content:encoded><![CDATA[<p>We are in the process of setting up our new system continuous deployment and status reports. Until this is complete, deployments will be done using our legacy system and this status page will be show &quot;Under Maintenance&quot;.</p>
<!--- language code: en -->
<div class="update-block">
          <div class="update-block-date">2020-04-24T22:34:31.677Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Fix</div>
            <div class="update-block-body">
<p>We have <a href="https://github.com/stencila/gaia/commit/af0ffe61dca99abcbd9c572926dbafe781771b90" target="_blank" rel="noopener noreferrer" class="external">resolved an issue</a> with publishing of the status page caused by the <code>CNAME</code> file being overwritten.</p>
</div></div></div>
<div class="update-block">
          <div class="update-block-date">2020-05-03T22:20:59.056Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Infrastructure</div>
            <div class="update-block-body">
<p>The <code>us-nw-1</code> cluster has been created in Google Cloud Platform's <code>us-west1-a</code> availability zone and we are beginning deployment to it.
When complete https://hub.stenci.la will be switch to point to this new cluster and we expect any disruption to service to be minimal.</p>
</div></div></div>
<div class="update-block">
          <div class="update-block-date">2020-05-03T22:20:59.056Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Complete</div>
            <div class="update-block-body">
<p>Initial deployment of Hub (v2.20.3) to the <code>us-nw-1</code> cluster has been completed.</p>
</div></div></div>
]]></content:encoded>
        </item>
    </channel>
</rss>